{% set version = "2.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-captioner
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/captioner_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/captioner/captioner_{{ version }}.tar.gz
  sha256: 72f92d757a47bae883cc95eb60a115c141aaf5eddcc15bc8068ea0faea15e775

build:
  merge_build_host: true  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('captioner')"           # [not win]
    - "\"%R%\" -e \"library('captioner')\""  # [win]

about:
  home: https://github.com/adletaw/captioner
  license: MIT
  summary: Provides a method for automatically numbering figures, tables, or other objects.  Captions can be displayed in full, or as citations. This is especially useful for adding figures and tables to R markdown documents without having to numbering them manually.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - tfenne

# Package: captioner
# Type: Package
# Title: Numbers Figures and Creates Simple Captions
# Version: 2.2.3
# Date: 2015-07-15
# Authors@R: person("Letaw", "Alathea", email = "alathea@zoology.ubc.ca", role = c("aut", "cre"))
# URL: https://github.com/adletaw/captioner
# BugReports: https://github.com/adletaw/captioner/issues
# Description: Provides a method for automatically numbering figures, tables, or other objects.  Captions can be displayed in full, or as citations. This is especially useful for adding figures and tables to R markdown documents without having to numbering them manually.
# License: MIT + file LICENSE
# Suggests: knitr
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2015-07-15 18:43:40 UTC; a
# Author: Letaw Alathea [aut, cre]
# Maintainer: Letaw Alathea <alathea@zoology.ubc.ca>
# Repository: CRAN
# Date/Publication: 2015-07-16 00:46:21
