appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jTqlB9tXQOecxGOp6o+YfP3tcSe87F43z19l6FEgnNgm/tNI6aySlyTciz54F3nr7LK5dOYBVMDPNwgEL6+NAHQHqA7N+ytuu75zmS+n283mjyXx0Pfvt+k5pxgxgGiKf9rqNyJtqSlAoaAvOOiLRkcCc6CubUDtu0uJxdVKC70lByyFQxGfFPXM8FjWZ077EXbQGP338EoE1WthzYojc3fSm07kEsIjKcgyk5P9VlAQSCXEPcxGNKdCTBmHHO0O+S4+Hcc3vgGij9BywSmc9YSNSXQvEyyBTsKTn7lGVQowp2p07wAeCFrnVTY7Z+stB9C8/FE6SOi+NYc+RuIMfpFGzH5tdv1cWMvR2r6HAuKCYzvRO6pufpp95G3cuJLBgX/XX1S+H/H/tBSTFD8TZgkNrUZSl+ItN+sgBx6PVr6ZU5B1Gt4f7Gru7BifrqJY/Yub/JZzxCCjuuFOUXCa4qBXs7NNmKUCU/RJEFA4BdoZzlhJw0ecELMs0rU4gq+S+YAUAWGKJAA2Xt3+xLoRVlL0asSFqD3uOi4cvVQkj/VRWPd0+KL+bgslgm/uArhJcxh2bOdXuEEpVfpkNDYADIAZeyVJw63WQLQvO9qvNYZ5a+bvulYI5ztZ5xz11EyKyQ2NHBrWVY6/0HokmXaNPWwP1iNOlvwJfKIWnnQGfME=}
